repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v1.19.0
  hooks:
  - id: pyupgrade
- repo: https://github.com/python/black
  rev: 19.3b0
  hooks:
  - id: black
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.7
  hooks:
  - id: flake8
- repo: https://github.com/asottile/blacken-docs
  rev: v1.1.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==19.3b0]
