trigger:
  branches:
    include: [dev, test-me-*]
  tags:
    include: ["*"]

# Run builds nightly to catch incompatibilities with new marshmallow releases
schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - dev
    always: "true"

resources:
  repositories:
    - repository: sloria
      type: github
      endpoint: github
      name: sloria/azure-pipeline-templates
      ref: refs/heads/sloria

jobs:
  - template: job--python-tox.yml@sloria
    parameters:
      toxenvs:
        - lint

        - py37-lowest
        - py37-marshmallow3
        - py310-marshmallow3
        - py310-marshmallowdev

        - docs
      os: linux
  - template: job--pypi-release.yml@sloria
    parameters:
      dependsOn:
        - tox_linux
